# Generated by Django 4.2.7 on 2023-12-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingmodel_filter_operator_and_more'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='mailing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_mail', to='mailing.mailingmodel'),
        ),
    ]
