# Generated by Django 4.2.7 on 2023-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('filter_properties', models.CharField(max_length=50)),
            ],
        ),
    ]
