# Generated by Django 4.2.7 on 2023-12-01 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmodel',
            name='filter_properties',
        ),
        migrations.AddField(
            model_name='mailingmodel',
            name='filter_operator',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='mailingmodel',
            name='filter_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
        ),
    ]
