# Generated by Django 4.2.7 on 2023-12-02 06:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailingmodel_filter_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmodel',
            name='filter_operator',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mailingmodel',
            name='filter_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, null=True, size=None),
        ),
    ]
