# Generated by Django 5.0 on 2023-12-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingmodel_filter_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField()),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailing.mailingmodel')),
            ],
        ),
    ]
