# Generated by Django 4.2.7 on 2023-11-28 08:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('operator_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=63)),
            ],
        ),
    ]
