# Generated by Django 4.2.7 on 2023-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_tagmodel_remove_clientmodel_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='operator_code',
            field=models.IntegerField(default=None),
        ),
    ]
