# Generated by Django 4.2.7 on 2023-12-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientmodel_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktagandclientmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientmodel'),
        ),
    ]
