stages:
  - test


build-job:
  stage: test
  image: docker
  script:
    - echo '$DEBUG' > .env
    - echo '$JWT_API' > .env
    - echo '$NAME_DB' > .env
    - echo '$PASSWORD_DB' > .env
    - echo '$SECRET_KEY' > .env
    - echo '$URL_API' > .env
    - echo '$USER_DB' > .env
    - docker-compose up --build --rm tests
    