stages:
  - test


test-job:
  stage: test
  image: docker
  services: 
    - docker:dind
  script:
    - echo "DEBUG=$DEBUG" >> .env
    - echo "JWT_API=$JWT_API" >> .env
    - echo "NAME_DB=$NAME_DB" >> .env
    - echo "PASSWORD_DB=$PASSWORD_DB" >> .env
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "URL_API=$URL_API" >> .env
    - echo "USER_DB=$USER_DB" >> .env
    - docker-compose up --build postgres -d
    - docker-compose up --build tests
  after_script:
  - if grep -q 'OK$' tests-1.log; then
      # Тесты пройдены, устанавливаем статус success
      set-pipeline-status "success"
    else
      # Тесты не пройдены, устанавливаем статус failed
      set-pipeline-status "failed" "Tests failed"
    fi
  